### PR TITLE
Update to Orleans 8.2

### PR DESCRIPTION
**Pull request by oising**
- update to orleans 8.2
- clean up new warnings

### CODE REVIEW

**Comment by VincentH-Net** [comment]
Thanks for the update @oising - it looks fine for `Example` and `Tests`.

However for the `Orleans.Multitenant` NuGet itself there is no need to update from 8.1; there are no breaking changes in 8.2 that would justify setting the lowest supported version to 8.2, and I would not want to force users to update their apps to 8.2 without good cause. (I did have to do that for 8.0 to 8.1 because of breaking changes in Orleans provider configuration)

When users update their app dependencies to Orleans 8.2, the Orleans.Multitenant NuGet will use 8.2 as well. I tested the existing Orleans.Multitenant 2.1.0 with Orleans >= 8.1.0 and the updated example + tests with Orleans 8.2 - all work fine, all use 8.2 then.

Could you update the PR to remove all changes within the NuGet project?
I suggest changing the PR title to "Update Example and Tests to Orleans 8.2"

**Comment by VincentH-Net** [comment]
> Could you update the PR to remove all changes within the NuGet project?

@oising do you have an ETA? I intend to release 2.2 on Monday, it would be nice if I could merge the 8.2 example and tests then (not necessary though - can be later)

**Comment by oising** [comment]
I'm on vacation for three weeks and away from the computer, so I could do it when I'm back, or feel free to add a commit yourself :)

**Comment by VincentH-Net** [comment]
> I'm on vacation for three weeks and away from the computer, so I could do it when I'm back, or feel free to add a commit yourself :)

@oising Ok, I'll merge your PR to it's feature branch and add a commit there - enjoy your vacation!

**Pull request merged**
